### ISSUE TITLE
Game scanner window partially non-responsive during game scan

### ISSUE THREAD

**Issue by Alphamplyer** [ProjectCeleste/Celeste_Launcher#43] opened 2020-01-05 20:50 UTC
Hi ! I suggest a small improvement.

It would be nice if the launcher could put itself above the other windows when we click on it. When it is hidden by another window.

**Comment by martinmine** [comment] 2020-01-08 19:45
Hi,
Thanks for your suggestion. We are in the middle of a major redesign of the launcher. You can read more about it here: https://forums.projectceleste.com/threads/celeste-launcher-3-0-beta-release.4477/
Can you check in the beta build if this issue is still present?

**Comment by Alphamplyer** [comment] 2020-01-08 21:22
This issue still present when we run a game scan on the new launcher ;)
Possibly due to the top screen constraint !

**Comment by martinmine** [comment] 2020-01-09 06:42
This sounds like a bug to me, however I am unable to reproduce it based on the details in this issue description. When I start a game scan, then hide the window by having another cover it partially, if I click on the game scanner window it still gets into focus. This is both from selecting it through the task bar or directly on the window itself. Could you provide a step-by-step instructions list on how to reproduce this issue?

**Comment by Alphamplyer** [comment] 2020-01-09 13:24
- open the launcher
- run a game scan
- click on another window (like explorer for my example)
- and only when the scan is in action, I can bring up the scan window in the foreground from time to time but not the one behind.

Exemple :
![Annotation 2020-01-09 142346](https://user-images.githubusercontent.com/42153930/72071283-b266b400-32eb-11ea-867c-c7a65d9e6a14.png)

**Comment by Alphamplyer** [comment] 2020-01-09 13:26
The window bug seems to occur only during file download, but i'm not sure about this information.

**Comment by martinmine** [comment] 2020-01-09 18:53
Thanks, the reason this happens is that the launcher is doing CPU-intensive work that blocks the UI thread. Some work has been put into preventing this from happening but it seems like it is not enough. I've seen this on some devices and thought this wasn't an issue any more.
To mitigate this further I've added a small patch that runs the entire game scan process in https://github.com/ProjectCeleste/Celeste_Launcher/pull/44/commits/f75dd7e683bac38e69af3e1edbfd4d6c4736ea56. Can you try out the build here https://ci.appveyor.com/project/Ryddag/celeste-launcher/builds/30005882/artifacts and see if you still experience the issue?

**Comment by Alphamplyer** [comment] 2020-01-09 20:47
the problem is solved for the scan window, but it is not yet what I thought. it would be nice to manage the two windows as a whole. For example, when you click on the scan window, the background window will also have to be in front.

This :
![Annotation 2020-01-09 214324](https://user-images.githubusercontent.com/42153930/72103269-24112300-3329-11ea-9e59-e699d45278d9.png)

Instead of this :
![Annotation 2020-01-09 142346](https://user-images.githubusercontent.com/42153930/72103282-2d01f480-3329-11ea-950d-ce5dad0b018d.png)

In addition, now, I launched four game scans and three of them produced an error :
![Annotation 2020-01-09 214628](https://user-images.githubusercontent.com/42153930/72103495-9da91100-3329-11ea-870f-bbfb0c5398f0.png)
Log File :
[launcherlog20200108.log](https://github.com/ProjectCeleste/Celeste_Launcher/files/4042426/launcherlog20200108.log)
[launcherlog20200109.log](https://github.com/ProjectCeleste/Celeste_Launcher/files/4042427/launcherlog20200109.log)
[launcherlog20200105.log](https://github.com/ProjectCeleste/Celeste_Launcher/files/4042428/launcherlog20200105.log)

**Comment by martinmine** [comment] 2020-01-09 21:21
It is intentional you cannot do other things in the launcher while the game scan is up but we might change this in the future. This is to prevent game files being modified while running the game scan. I've opened another issue here https://github.com/ProjectCeleste/Celeste_Launcher/issues/45 to deal with the error message you are getting as that is a separate issue than what is being discussed here.

**Comment by Alphamplyer** [comment] 2020-01-09 21:24
I was not asking to be able to do something about it, just to pass the whole application in front ;)

**Comment by martinmine** [comment] 2020-01-09 21:53
Ok, I get you; you want to essentially group the windows together so that when you have the game scanner with file explorer between the game scanner and the main menu, the main menu will go in front of file explorer. It is not intentional behavior, but I think it would be a nice quality-of-life improvement. I will have a look into it and see how this can be done.

**Comment by Alphamplyer** [comment] 2020-01-09 21:58
That's what I was trying to say ! My english is not very good so it makes things a little confusing.

**Comment by Alphamplyer** [comment] 2020-01-09 21:58
sry miss x)

**Comment by martinmine** [comment] 2020-01-09 22:00
No problem. This was quite easy to do and is fixed in commit https://github.com/ProjectCeleste/Celeste_Launcher/pull/44/commits/82b574ea65c8540f9b121fa3708954c8f28df647. However, this must be done for other dialog boxes as well so I will look more into this tomorrow.

**Comment by martinmine** [comment] 2020-01-09 22:17
Change implemented for other dialogs in https://github.com/ProjectCeleste/Celeste_Launcher/pull/44/commits/ea61d216350b205e2e65c19385e77057f68bed99.
I will go ahead and close this issue for now.

**Closed** 2020-01-09 22:18 UTC
Labels: bug
